### ISSUE TITLE
Analyse and Create service stubs

### ISSUE THREAD

**Issue by use-to** [helpwave/services#131]
There are some crud-related endpoints missing.
1. Analyse and locate these endpoints
2. Create stubs with no-operation "handling" these things
3. Mark them as todo and create issues

**Comment by MaxSchaefer** [comment]
The new issues should be scoped by service and only be opened after the pr is merged.

**Comment by use-to** [comment]
Services touch by this issue:
```yaml
services:
  user:
    - Organization (crud)
    - User (crud)
  task:
    - Patient (crud)
    - Room (crud)
    - Task (crud)
    - Ward (crud)
```
